// app/api/payments/yoco-webhook/route.ts
import { NextRequest } from "next/server";
import { db } from "@/lib/DB/prisma";
import { verifyYocoWebhook, YOCO_CONFIG } from "@/lib/payments/yoco";
import { sendOrderConfirmedEmail } from "@/lib/emails/mailer";

export const dynamic = "force-dynamic";

export async function POST(req: NextRequest) {
  const rawBody = await req.text();

  // 1. Require the secret (Fail Closed)
  // If the secret is missing, we reject the request entirely to prevent spoofing.
  if (!YOCO_CONFIG.webhookSecret) {
    console.error("[Yoco Webhook] YOCO_WEBHOOK_SECRET is not configured. Rejecting request.");
    return new Response("Webhook secret not configured", { status: 500 });
  }

  // 2. Reject invalid signatures
  const sigOk = verifyYocoWebhook(
    rawBody,
    {
      id:        req.headers.get("webhook-id"),
      timestamp: req.headers.get("webhook-timestamp"),
      signature: req.headers.get("webhook-signature"),
    },
    YOCO_CONFIG.webhookSecret
  );
  if (!sigOk) {
    console.error("[Yoco Webhook] Invalid signature", {
      hasId:        !!req.headers.get("webhook-id"),
      hasTimestamp: !!req.headers.get("webhook-timestamp"),
      hasSignature: !!req.headers.get("webhook-signature"),
      secretLooksValid: YOCO_CONFIG.webhookSecret.trim().startsWith("whsec_"),
    });
    return new Response("Invalid signature", { status: 400 });
  }

  let event: any;
  try { 
    event = JSON.parse(rawBody); 
  } catch { 
    return new Response("Invalid JSON", { status: 400 }); 
  }

  console.log(`[Yoco Webhook] Event: ${event.type}`);

  try {
    let response: Response | void = undefined;
    if (event.type === "payment.succeeded") {
      response = await processSuccess(event.payload);
    } else if (event.type === "payment.failed") {
      response = await processFailure(event.payload);
    }
    
    // If a specific error/success response was generated by the handlers, return it
    if (response) return response;
  } catch (err) {
    console.error("[Yoco Webhook] Error:", err);
    return new Response("Internal Server Error", { status: 500 });
  }

  // Default success response for Yoco
  return new Response("OK", { status: 200 });
}

async function processSuccess(payload: any): Promise<Response | void> {
  const checkoutId = payload.metadata?.checkoutId ?? payload.checkoutId;
  const orderId = payload.metadata?.orderId;

  if (!orderId && !checkoutId) {
    console.error("[Yoco Webhook] No orderId or checkoutId in payload");
    return new Response("Missing order identifiers", { status: 400 });
  }

  const payment = await db.payment.findFirst({
    where: {
      OR: [
        { orderId: orderId ?? "" },
        { transactionId: checkoutId ?? "" },
      ],
      provider: "yoco",
    },
    include: { order: true },
  });

  if (!payment) { 
    console.error("[Yoco Webhook] Payment not found"); 
    return new Response("Payment not found", { status: 404 }); 
  }
  
  if (payment.status === "SUCCESS") { 
    console.log("[Yoco Webhook] Already processed"); 
    return new Response("Already processed", { status: 200 }); 
  }

  // 3. Require matching amount and currency (Strict Validation)
  const receivedAmount = payload.amount ?? payload.amountInCents;
  const expectedAmount = Number(payment.order.total);
  const receivedCurrency = payload.currency ?? "ZAR";

  // Use typeof check to ensure it's a valid number and strictly equal to expected
  if (typeof receivedAmount !== "number" || receivedAmount !== expectedAmount) {
    console.error(`[Yoco Webhook] Amount mismatch: expected ${expectedAmount}, got ${receivedAmount}`);
    return new Response("Amount mismatch", { status: 400 });
  }

  if (receivedCurrency !== "ZAR") {
    console.error(`[Yoco Webhook] Currency mismatch: expected ZAR, got ${receivedCurrency}`);
    return new Response("Currency mismatch", { status: 400 });
  }

  // Only update the database after all security checks pass
  await db.payment.update({
    where: { id: payment.id },
    data:  { status: "SUCCESS", transactionId: payload.id ?? checkoutId },
  });
  
  await db.order.update({ 
    where: { id: payment.orderId }, 
    data: { status: "PAID" } 
  });

  // Await the email: on Vercel the function is frozen once the response is
  // returned, so a fire-and-forget promise can be dropped before it sends.
  // Failures are caught so they never turn a successful payment into a 500
  // (which would make Yoco retry the webhook).
  try {
    const emailParams = await buildOrderEmailParams(payment.orderId);
    await sendOrderConfirmedEmail(emailParams);
  } catch (err) {
    console.error("[Yoco Webhook] Order confirmation email failed:", err);
  }

  console.log(`[Yoco Webhook] ✅ Order ${payment.orderId} marked as PAID`);
}

async function processFailure(payload: any): Promise<Response | void> {
  const checkoutId = payload.metadata?.checkoutId ?? payload.checkoutId;
  const payment = await db.payment.findFirst({
    where: { transactionId: checkoutId, provider: "yoco" },
  });
  
  if (!payment) {
    console.error("[Yoco Webhook] Payment not found for failure");
    return new Response("Payment not found", { status: 404 });
  }
  
  await db.payment.update({ 
    where: { id: payment.id }, 
    data: { status: "FAILED" } 
  });
  
  console.log(`[Yoco Webhook] ❌ Payment failed for order ${payment.orderId}`);
}

async function buildOrderEmailParams(orderId: string) {
  const order = await db.order.findUnique({
    where:   { id: orderId },
    include: {
      user:    { select: { name: true, email: true } },
      address: true,
      items:   { include: { variant: { include: { product: { select: { name: true } } } } } },
    },
  });
  if (!order) throw new Error(`Order ${orderId} not found`);
  return {
    to:           order.user.email,
    customerName: order.user.name,
    orderId:      order.id,
    orderDate:    new Date(order.createdAt).toLocaleDateString("en-ZA", { day: "numeric", month: "long", year: "numeric" }),
    items: order.items.map(item => ({
      name:     item.variant.product.name,
      variant:  [item.variant.color, item.variant.length ? `${item.variant.length}"` : null].filter(Boolean).join(" · ") || "Standard",
      quantity: item.quantity,
      price:    Number(item.price),
    })),
    subtotal: Number(order.total),
    shipping: 0,
    total:    Number(order.total),
    address: order.address ? {
      fullName: order.address.fullName, street: order.address.street,
      city: order.address.city, province: order.address.province,
      postalCode: order.address.postalCode, country: order.address.country,
    } : { fullName: "", street: "", city: "", province: "", postalCode: "", country: "South Africa" },
  };
}